version: '3'
services:
  node_api:
    container_name: codec_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # API port
      - "8080:8080" # Auth port
      - "8800:8800" # Socket port
    environment:
      - API_PORT=${API_PORT}
      - AUTH_PORT=${AUTH_PORT}
      - SOCKET_PORT=${SOCKET_PORT}
      - MONGODB_URI=${MONGODB_URI}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - MAILER_USERNAME=${MAILER_USERNAME}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: codec_database
    ports:
      - "27017:27017"  # Map the MongoDB port
    volumes:
      - mongodb_data:/data/db  

volumes:
  mongodb_data:  